## 正式 环境
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jishi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 123456
      minimum-idle: 10        # 连接池最小连接
      maximum-pool-size: 100  # 连接池最大连接
      auto-commit: true       # 自动提交
      pool-name: JishiHikariCP  # 连接池名称
      idle-timeout: 600000    # 连接最大空闲时间(毫秒)，超过后删除
      max-lifetime: 28740000  # 连接的最长生命周期。当连接达到此超时时，即使最近使用过，它也会从池中退役。正在使用的连接永远不会被退休，只有当它空闲时才会被删除
      connection-test-query: SELECT 1 FROM DUAL # 测试SQL
  redis:
    # 地址
    host: 127.0.0.1
    # 端口号
    port: 6379
    # 密码
    password:
    # 超时时间，单位毫秒
    timeout: 10000
    # 数据库编号
    database: 0
    # 配置lettuce
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池最大连接数（使用负值表示没有限制,不要配置过大，否则可能会影响redis的性能）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）；单位毫秒
        max-wait: 5000
      #关闭超时时间；单位毫秒
      shutdown-timeout: 2000
